# -*- coding: utf-8 -*-
"""Angle_Endoding.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oxWCYN6SyuU6I_2DjFey_LT0ga7Ie2i
"""

# !pip install --upgrade qiskit
# !pip install qiskit
# !pip install qiskit-aer

from qiskit import QuantumCircuit, transpile, assemble
from qiskit.visualization import plot_histogram
from qiskit_aer import Aer  # Import Aer from the qiskit_aer module

# Create a quantum circuit with 2 qubits
qc = QuantumCircuit(2)
# Encode classical data using rotation gates
angle1 = 0.3  # Example angle for encoding qubit 0
angle2 = 0.6  # Example angle for encoding qubit 1
qc.rx(angle1, 0)
qc.ry(angle2, 1)

# Simulate quantum circuit
simulator = Aer.get_backend('statevector_simulator')
result = simulator.run(qc).result()
statevector = result.get_statevector()
print(statevector)